# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: true
  
spring.application.admin:
  enabled: false
  jmx-name: org.springframework.boot:type=Admin,name=SpringApplication

spring.data.mongodb:
  host: localhost
  port: 32773


magic.8.ball:
  log-responses: true